### PR TITLE
update python requirements

### PR DESCRIPTION
**Pull request by EQt**
`graphfl` tool does not work in python3, or without `matplotlib` installed

### CODE REVIEW

**Comment by tansey** [comment]
Thanks! I'm actually now in the process of removing the matplotlib dependency for graphfl. It should be gone now, but I'll merge in your changes and edit the docs appropriately.

**Comment by tansey** [comment]
Done! Please let me know if you still have problems with needing matplotlib.

The python 2 dependency can be fixed as well, but it's a good point to note that it's not currently compatible. I have some division-by-int stuff in there that I really should hunt down and fix.

**Comment by EQt** [comment]
Seems like `matplotlib` is not needed anymore when invoking `graphfl`.
By the way: You could also easily check that by creating a new [conda](http://conda.pydata.org/miniconda.html) environment.

**Comment by EQt** [comment]
Have you thought about using [tavis-ci](http://conda.pydata.org/docs/travis.html) for automated unit tests?
I can help you with that if you want...

**Comment by tansey** [comment]
I think automated unit tests might be a bit overkill at this point, given that everything already works and is pretty stable, but thanks! If I start adding more stuff to the project, I'll circle back to this. :)

**Pull request merged**
